// Copyright (c) 2024, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source is governed by a
// BSD-style license that can be found in the LICENSE file.

// GENERATED FILE. DO NOT EDIT.
// ignore_for_file: constant_identifier_names

part of "../example.dart";

// START GENERATED CHARCODES
// Generated by
// dart run charcode -v -H -o example/src/charcodes.dart -p_ 'Example!()'

/// Character `!`.
const int _exclamation = 0x21;

/// Character `(`.
const int _lparen = 0x28;

/// Character `)`.
const int _rparen = 0x29;

/// Character `E`.
const int _E = 0x45;

/// Character `a`.
const int _a = 0x61;

/// Character `e`.
const int _e = 0x65;

/// Character `l`.
const int _l = 0x6c;

/// Character `m`.
const int _m = 0x6d;

/// Character `p`.
const int _p = 0x70;

/// Character `x`.
const int _x = 0x78;

// END GENERATED CHARCODES
